# Generated by Django 6.0 on 2025-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resume_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('activity_id', models.CharField(help_text='Example: 7340284008175411200', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
