# Generated by Django 6.0 on 2025-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_linkedinpost_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='My Resume', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
